<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>c422a316-5851-4c99-b16f-ad843cb9db31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1t:']/div[2]/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;radix-\:r1t\:&quot;] > .pt-4 > div:nth-child(4) > div:nth-child(3) > .w-\[430px\]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cb81dae-67f1-4852-b899-c5149cc26dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[430px] px-4 py-3 bg-teal-700 text-white font-medium tracking-wide rounded-lg hover:bg-teal-800 overflow-visible</value>
      <webElementGuid>ecf8cb6d-00b2-43eb-b854-87b03217deea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>76ec89be-74c2-45b9-8fa3-f2d76c45d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1t:&quot;)/div[@class=&quot;pt-4 flex flex-col gap-1&quot;]/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;mt-2 w-full flex flex-row justify-center items-center&quot;]/button[@class=&quot;w-[430px] px-4 py-3 bg-teal-700 text-white font-medium tracking-wide rounded-lg hover:bg-teal-800 overflow-visible&quot;]</value>
      <webElementGuid>429b39c3-7176-4ec1-afe7-96a7137a4c13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1t:']/div[2]/div[3]/div[2]/button</value>
      <webElementGuid>ca06ef80-de75-4c46-96b5-01bc2dd50ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[20]/following::button[1]</value>
      <webElementGuid>c692a92f-649d-4408-8e4d-271a142bb3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−'])[20]/following::button[2]</value>
      <webElementGuid>79979dd9-02f7-4edf-9ae1-c2af6f484a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[20]/preceding::button[1]</value>
      <webElementGuid>0288bde3-30f0-4fdd-baae-2b56b3a0f8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[43]/div[2]/div[3]/div[2]/button</value>
      <webElementGuid>69f70301-0734-49ee-bd3d-c8885c801e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>d5e2ac19-3c67-4cc7-85b4-a622b02fa7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
