<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>48d10f61-10b8-4c8a-a1cf-5b5bad27f669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;20 image-product iPad Pro Smart Keyboard Folio 12.9-inch White aksesoris iPad Rp 4.139.000 Rp 5.159.000 Edit&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2c3c0ca-bb8c-4499-b744-922953336c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-md text-sm font-semibold tracking-wide w-full hover:underline</value>
      <webElementGuid>d9072dda-0798-4222-bbdf-6bfb4aed98ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b653aa8a-a22b-4c62-9f28-3a7ba408cd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>983aa05d-4bc1-4124-bf43-e9027d3fb4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3fb0c03-fed6-48b4-a912-dd7e8dc4bcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1t:</value>
      <webElementGuid>d706c00a-a3d1-486e-b28a-7966e6a4cdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>3dbaa9e9-1358-4de6-9d37-407f1263e64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>49536266-250b-4057-8b40-d143d540e98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full max-h-screen mx-auto pr-8 font-inter&quot;]/div[@class=&quot;lg:pl-72 mx-8&quot;]/section[1]/div[@class=&quot;relative overflow-x-auto border-[1px] border-gray-100 sm:rounded-lg mb-16&quot;]/table[@class=&quot;z-0 w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400&quot;]/tbody[1]/tr[@class=&quot;border-b border-gray-200 dark:border-gray-700&quot;]/td[@class=&quot;min-w-[150px] px-6 py-4&quot;]/button[@class=&quot;rounded-md text-sm font-semibold tracking-wide w-full hover:underline&quot;]</value>
      <webElementGuid>a0f9b4c4-9edb-4c67-a25f-beea9709a579</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>9897cfe2-37b4-4099-885b-e0da011b75c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[5]/button</value>
      <webElementGuid>25320c95-33cc-4eb3-a313-393791db5c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>1ecfee54-7987-4ce5-8caa-590ac215cd97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
