<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>d4608cb8-c2dc-4085-a701-8a38c58dccc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r1t:']/div[2]/div[3]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;radix-\:r1t\:&quot;] > .pt-4 > div:nth-child(4) > div:nth-child(3) > .w-\[430px\]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>287b81af-5b23-419a-b106-36996d0e32ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-[430px] px-4 py-3 bg-teal-700 text-white font-medium tracking-wide rounded-lg hover:bg-teal-800 overflow-visible</value>
      <webElementGuid>986e806c-6a6e-4c49-ae4e-ac695a956fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>420046f0-cb22-41a0-8013-4c8004d7c176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1t:&quot;)/div[@class=&quot;pt-4 flex flex-col gap-1&quot;]/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;mt-2 w-full flex flex-row justify-center items-center&quot;]/button[@class=&quot;w-[430px] px-4 py-3 bg-teal-700 text-white font-medium tracking-wide rounded-lg hover:bg-teal-800 overflow-visible&quot;]</value>
      <webElementGuid>6e896797-9809-45e9-a08e-7a81583bc405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1t:']/div[2]/div[3]/div[2]/button</value>
      <webElementGuid>c89b5b2f-137b-4144-890c-b3e7fe6bdd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[20]/following::button[1]</value>
      <webElementGuid>6fa0b9b2-2566-4f68-9342-604385a7b199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='−'])[20]/following::button[2]</value>
      <webElementGuid>7b9fa94d-19ed-49c8-b5ce-f7335f3a36b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[20]/preceding::button[1]</value>
      <webElementGuid>ab4d1e21-dd78-4186-8b6f-3653d638346a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[43]/div[2]/div[3]/div[2]/button</value>
      <webElementGuid>52d56fa2-3a38-4456-b0ac-47ff8e597101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>4e95c69c-d6e0-43c6-b78d-11e5aa80740c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
