<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_qty_stock</name>
   <tag></tag>
   <elementGuidId>8109d42f-2b45-4dd0-9866-43a9c2a80795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='custom-input-number'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;radix-\:r1t\:&quot;] > .pt-4 > div:nth-child(4) > .mb-2 > div > input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>780964f9-e45e-46d2-88ca-fd85b0564f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>outline-none focus:outline-none text-center w-10 bg-neutral-100 font-semibold text-sm lg:text-base hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-neutral-700</value>
      <webElementGuid>0fde219d-b8a7-44f2-8e01-24722a0479ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f5392b6b-a40d-4525-912a-002f8aad5810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db7b8684-682c-4ae9-984d-6f6e50a3c5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>custom-input-number</value>
      <webElementGuid>832cba9f-d1d9-4204-96d2-68df4f21e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r1t:&quot;)/div[@class=&quot;pt-4 flex flex-col gap-1&quot;]/div[@class=&quot;flex flex-col items-center justify-center&quot;]/div[@class=&quot;mb-2 flex flex-row justify-center items-center gap-4&quot;]/div[@class=&quot;flex flex-row w-32 h-8 rounded-lg relative bg-transparent mt-2&quot;]/input[@class=&quot;outline-none focus:outline-none text-center w-10 bg-neutral-100 font-semibold text-sm lg:text-base hover:text-black focus:text-black  md:text-basecursor-default flex items-center text-neutral-700&quot;]</value>
      <webElementGuid>dae9698f-f512-4ae5-aad8-c4912ccd66cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='custom-input-number'])[20]</value>
      <webElementGuid>91f3d321-74bb-4321-acdb-a49e45a63bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r1t:']/div[2]/div[3]/div/div/input</value>
      <webElementGuid>9d35be15-859a-4f69-9c84-fda233a8e8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[43]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>f736a46e-065f-4bb6-9a09-c901e9d01d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'custom-input-number']</value>
      <webElementGuid>2c3602af-6d66-4002-bba4-4478367c4c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
