<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_List Produk_fill-white</name>
   <tag></tag>
   <elementGuidId>e3000970-6097-41cc-8561-4690fefa830e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.side-link.z-2001.active > img.fill-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='icon'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;icon Atur Stok&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87b5051b-3e1f-4d9c-8a59-7388e5111c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>8825c819-3e1a-44fb-88fd-fea477826b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8d1e2581-e766-4636-9980-2ec67982273f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3c83a1d4-23ef-48fb-9e9d-776db3de9a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>58f80864-365c-44cb-9932-b1960905afb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>954d936a-bdac-4e17-990a-01bfb2862c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e5705fe5-27f9-49ec-aca4-7754165cee04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill-white</value>
      <webElementGuid>c7ce939c-a958-4f93-abfd-26d91556508d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/stock.svg</value>
      <webElementGuid>076105a4-67d7-4ce2-85b1-fb23d7c8f518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full max-h-screen mx-auto pr-8 font-inter&quot;]/aside[@class=&quot;-left-72 w-0 lg:left-0 lg:w-72 fixed flex z-50 h-screen flex-col space-y-2 border-r dark:border-[#1E293B] dark:bg-[#0F172A] bg-white p-2 peer-focus:left-0 transition-all delay-100 duration-100&quot;]/a[@class=&quot;side-link z-2001 active&quot;]/img[@class=&quot;fill-white&quot;]</value>
      <webElementGuid>8e74bb22-e523-4886-9b7f-46781e8c20de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>70d69df2-0e32-4474-b7c9-868cdd295f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>4a013ea9-b431-47eb-989a-f814f5a488bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon' and @src = '/icons/stock.svg']</value>
      <webElementGuid>a0965070-39f8-46b7-afc8-ccb3c9eb36be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
