<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_List Produk_inline transition-all durat_356faf</name>
   <tag></tag>
   <elementGuidId>3dee0f37-17fe-495f-b3f3-219b4611cc42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inline.transition-all.duration-200.text-indigo-700.ease-nav-brand.mr-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='main-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;main-logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e633f6cb-2431-46b6-bc56-3004f489974b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>main-logo</value>
      <webElementGuid>07f2251e-5172-412e-b4bc-c78cc1bcb6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>315cadd7-d8da-4ccb-94f1-4c464cdc6e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>9117b8c1-5a13-43cd-8773-d27e9ac96091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2967f9d2-01c0-45c4-8716-3107cc94d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>bcae96a7-5666-47ee-9c7e-40904c671553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f35d17f9-7508-40ff-9dc3-90ff8d17c722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline transition-all duration-200 text-indigo-700 ease-nav-brand mr-4</value>
      <webElementGuid>0ec66b70-1465-4c82-b66a-7fe26867a0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/growia.svg</value>
      <webElementGuid>1f681915-fe78-4d97-af06-4eb8fca98831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full max-h-screen mx-auto pr-8 font-inter&quot;]/aside[@class=&quot;-left-72 w-0 lg:left-0 lg:w-72 fixed flex z-50 h-screen flex-col space-y-2 border-r dark:border-[#1E293B] dark:bg-[#0F172A] bg-white p-2 peer-focus:left-0 transition-all delay-100 duration-100&quot;]/div[@class=&quot;h-19.5&quot;]/a[@class=&quot;flex items-center justify-center space-x-1 rounded-md px-2 py-4&quot;]/img[@class=&quot;inline transition-all duration-200 text-indigo-700 ease-nav-brand mr-4&quot;]</value>
      <webElementGuid>16e749b0-1e62-4241-8d78-b06a3c0c8b0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='main-logo']</value>
      <webElementGuid>c84b18f8-001e-4933-bafe-68c80f5ecc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1ed28045-3e0c-42a7-8bd0-befa5129165d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'main-logo' and @src = '/icons/growia.svg']</value>
      <webElementGuid>03ecf25a-5e73-44f6-b71e-b73e1f757c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
