<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_List Produk_inline transition-all durat_356faf</name>
   <tag></tag>
   <elementGuidId>ba344dc1-1fc9-4551-826d-af2fc466f8cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.inline.transition-all.duration-200.text-indigo-700.ease-nav-brand.mr-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='main-logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;main-logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>73cae5a3-09e7-41d7-9cc1-330d8c483b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>main-logo</value>
      <webElementGuid>6694e204-a795-4b47-93bc-cf85be54783f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>1fd22996-a13a-464e-a807-82db8521d9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4a4a7588-3122-4cad-b29e-c7cb647bca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>01f52f4a-642b-4ebd-bcab-3a5e38238027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0c9e7d07-baf1-424b-a9e8-a25a38ae6950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6af2ad94-6abd-4558-aa99-a3605d49c5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline transition-all duration-200 text-indigo-700 ease-nav-brand mr-4</value>
      <webElementGuid>c99fa5be-e6f2-4270-a676-c2f3caa65692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/growia.svg</value>
      <webElementGuid>9638defd-fd04-471b-9a9c-c91b086c631b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full dark:bg-[#0F172A] max-h-screen mx-auto font-inter&quot;]/aside[@class=&quot;-left-72 w-0 lg:left-0 lg:w-72 fixed flex z-50 h-screen flex-col space-y-2 border-r dark:border-[#1E293B] dark:bg-[#0F172A] bg-white p-2 peer-focus:left-0 transition-all delay-100 duration-100&quot;]/div[@class=&quot;h-19.5&quot;]/a[@class=&quot;flex items-center justify-center space-x-1 rounded-md px-2 py-4&quot;]/img[@class=&quot;inline transition-all duration-200 text-indigo-700 ease-nav-brand mr-4&quot;]</value>
      <webElementGuid>3e261078-ecdf-4eab-9543-3a5f8ce7d1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='main-logo']</value>
      <webElementGuid>ce3794da-c790-4d6e-92a0-967bef51f028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>477d373a-5f63-4abe-9db6-c78520eda91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'main-logo' and @src = '/icons/growia.svg']</value>
      <webElementGuid>4e6a21cf-5964-492c-a943-563242205eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
