<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_List Produk_fill-white</name>
   <tag></tag>
   <elementGuidId>71becc56-dee5-4844-9504-680d6142588c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fill-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;icon List Produk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97d54aed-1e50-4dd1-8a98-c84bae3b6b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>11d6ac67-46a7-4e7d-9ac6-754695517fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ab3e2722-3219-4760-9ece-8804880d16e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2d1ba952-0487-47c2-8cb9-ca2a914ed49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3901680f-7395-426c-b963-5ced5de4702c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ff6a049d-f64b-4b19-a756-c801b82e6e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>adff2bc8-b40c-4403-88f9-7232fbc9f4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill-white</value>
      <webElementGuid>3e8e3aa6-5bd0-41bb-8a30-1fb3f1a1a9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/add-product.svg</value>
      <webElementGuid>8cbcf435-b55c-4b0c-bd66-ea2e5e6117bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full dark:bg-[#0F172A] max-h-screen mx-auto font-inter&quot;]/aside[@class=&quot;-left-72 w-0 lg:left-0 lg:w-72 fixed flex z-50 h-screen flex-col space-y-2 border-r dark:border-[#1E293B] dark:bg-[#0F172A] bg-white p-2 peer-focus:left-0 transition-all delay-100 duration-100&quot;]/a[@class=&quot;side-link z-2001 active&quot;]/img[@class=&quot;fill-white&quot;]</value>
      <webElementGuid>e5c933e8-2770-4584-81d6-c12af4eb038a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>f029e4a5-ae36-42b0-ae80-896a754d59cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/a/img</value>
      <webElementGuid>2a5ab6a9-2a69-49c1-ba8f-174fba603e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon' and @src = '/icons/add-product.svg']</value>
      <webElementGuid>c5aed3f6-6c55-4d1a-8747-cd7087d8768f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
