<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Retype Password_retypePassword</name>
   <tag></tag>
   <elementGuidId>f77777bf-a511-4ca3-84b4-6e5fd3896944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='retypePassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;retypePassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Retype password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fe3d019-3f01-40bc-aae7-e7dbdb4b0697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-border w-full rounded-md shadow-sm transition-all px-4 py-2 bg-neutral-200 text-teal-800 placeholder:text-neutral-500</value>
      <webElementGuid>11be9c46-b341-4bd3-ae3c-3e5d15a9c2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Retype password</value>
      <webElementGuid>7019f33f-84a9-45a3-b257-b5dd32c5e272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e0db3384-7192-4ab2-95aa-9e7539e5f50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>22e15d23-2487-4d1b-9e49-a90fec7f5e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>retypePassword</value>
      <webElementGuid>44f360dd-76e9-4c20-86a1-6ad8ec0b94cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-form&quot;)/div[@class=&quot;text-sm&quot;]/div[@class=&quot;flex flex-col justify-between col-span-12 gap-2&quot;]/input[@class=&quot;box-border w-full rounded-md shadow-sm transition-all px-4 py-2 bg-neutral-200 text-teal-800 placeholder:text-neutral-500&quot;]</value>
      <webElementGuid>df08a25f-a364-45ea-bc88-881824a197bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='retypePassword']</value>
      <webElementGuid>d9c96b92-f753-49c6-b60b-22e119f69478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin-form']/div[4]/div/input</value>
      <webElementGuid>ff8446fe-5da1-4a63-901f-1887e44fcf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ecd121f0-5eb2-4d7c-8ef1-e66528a75c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Retype password' and @type = 'password' and @name = 'retypePassword']</value>
      <webElementGuid>c06cc68a-9d0d-43c6-ad7d-1717bd227f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
