<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>37e44925-4176-4cc6-b442-387abf4d8066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;20 image-product iPad Pro Smart Keyboard Folio 12.9-inch White aksesoris iPad Rp 4.139.000 Rp 5.159.000 Edit&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>672eacd9-152d-4152-ab8c-0e88e5cb8fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-md text-sm font-semibold tracking-wide w-full hover:underline</value>
      <webElementGuid>77bf36b2-51c8-460e-adfb-fd7a90da7d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4c00de1-c03a-4e5d-8249-f687b6509faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>65dd346d-6c60-4f48-ac87-118c97bba149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>244a743e-5802-4028-9137-ed8e2bc568c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1t:</value>
      <webElementGuid>548868b0-9241-40e8-a2a8-54c4a0243917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>4174ca23-c5e4-4c99-923b-5c28eb61b014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>c6eb2ec9-9d61-41c4-b38b-95092fbf640b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;w-full max-h-screen mx-auto pr-8 font-inter&quot;]/div[@class=&quot;lg:pl-72 mx-8&quot;]/section[1]/div[@class=&quot;relative overflow-x-auto border-[1px] border-gray-100 sm:rounded-lg mb-16&quot;]/table[@class=&quot;z-0 w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400&quot;]/tbody[1]/tr[@class=&quot;border-b border-gray-200 dark:border-gray-700&quot;]/td[@class=&quot;min-w-[150px] px-6 py-4&quot;]/button[@class=&quot;rounded-md text-sm font-semibold tracking-wide w-full hover:underline&quot;]</value>
      <webElementGuid>efe803c0-0adf-462e-9ac4-c8e87e47d8f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>54a604a5-917b-450f-afb2-404993e9e1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[5]/button</value>
      <webElementGuid>2c148e14-2cc1-42d9-8f63-fa3b7c5fe896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>8071c9e1-db5a-4fdc-bfce-b096db48f659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
