<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_iPhone_lucide lucide-user p-0 stroke-1.5px</name>
   <tag></tag>
   <elementGuidId>3ddef5b0-319b-4eab-9846-ce8123395c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone'])[1]/preceding::*[name()='svg'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;0iPhone iPad Mac Aksesoris&quot;i >> internal:role=link >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>aacb9738-9060-47df-8795-1beaa996f5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>92cc036b-a1f4-4cac-9481-fa82863ef387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>93e9b12e-3c20-4e2d-a136-6d00872d000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>26f054bc-2257-441b-9d5c-030151b88031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>b0409889-2e72-4496-8800-b82b4b79aa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>bd5835d2-a745-4561-88d4-aedfcab6a574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>2440165e-92f1-4b95-8f90-59ba9981d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f6e154ea-e0fb-42ed-a532-6ea4439f8214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>c599716f-4a01-40b9-bc67-cbc69017d63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>51fbf6a9-368c-4c8e-a6ee-e2f615fd1faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-user p-0 stroke-[1.5px]</value>
      <webElementGuid>aa3d7b28-46e3-429a-8bcb-94fdd699df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_aaf875&quot;]/div[@class=&quot;fixed z-[2] bg-white h-[64px] md:h-auto w-full py-[6px] flex flex-col justify-center items-center border-b-[1px] border-gray-200&quot;]/div[@class=&quot;w-full grid grid-cols-3 justify-center items-center&quot;]/div[@class=&quot;w-full pr-6 xl:pr-8 flex flex-row gap-1 justify-end items-center&quot;]/a[@class=&quot;p-2 hover:bg-green100 rounded-lg&quot;]/svg[@class=&quot;lucide lucide-user p-0 stroke-[1.5px]&quot;]</value>
      <webElementGuid>318ab6ef-4235-4f68-868f-f25e6047edb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>389239ae-5de2-42b3-a14c-1512d5f14e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad'])[1]/preceding::*[name()='svg'][4]</value>
      <webElementGuid>98b5296c-4d7e-4fdf-9c18-bc6ff4decc3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
